create extension if not exists pgcrypto;

create table if not exists public.admin_users (
    id uuid primary key default gen_random_uuid(),
    username text not null unique,
    display_name text not null,
    password_hash text not null,
    role text not null check (role in ('viewer', 'admin', 'super_admin')),
    active boolean not null default true,
    failed_login_count integer not null default 0 check (failed_login_count >= 0),
    locked_until timestamptz,
    last_login_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.teachers (
    id text primary key,
    first_name text not null,
    last_name text not null,
    active boolean not null default true,
    created_by_admin_id uuid references public.admin_users(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.qr_tokens (
    token_id uuid primary key,
    teacher_id text not null references public.teachers(id),
    payload jsonb not null,
    signature_hash text not null,
    issued_by_admin_id uuid references public.admin_users(id),
    revoked boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    teacher_id text not null references public.teachers(id),
    date date not null,
    time time not null,
    action text not null check (action in ('IN', 'OUT')),
    payload_hash text not null,
    signature text not null,
    signing_key_id text not null,
    qr_token_id uuid references public.qr_tokens(token_id),
    source text not null check (source in ('manual', 'qr', 'manual_scan_fallback')),
    created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    actor_admin_id uuid references public.admin_users(id),
    actor_username text,
    action text not null,
    entity_type text,
    entity_id text,
    details jsonb not null default '{}'::jsonb,
    ip_address text,
    user_agent text,
    created_at timestamptz not null default now()
);

create index if not exists idx_attendance_teacher_id_id on public.attendance (teacher_id, id desc);
create index if not exists idx_attendance_date on public.attendance (date);
create index if not exists idx_qr_tokens_teacher_id on public.qr_tokens (teacher_id);
create index if not exists idx_audit_logs_actor_created on public.audit_logs (actor_admin_id, created_at desc);
create index if not exists idx_audit_logs_action_created on public.audit_logs (action, created_at desc);

alter table public.admin_users enable row level security;
alter table public.teachers enable row level security;
alter table public.qr_tokens enable row level security;
alter table public.attendance enable row level security;
alter table public.audit_logs enable row level security;

revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.teachers from anon, authenticated;
revoke all on table public.qr_tokens from anon, authenticated;
revoke all on table public.attendance from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;

comment on table public.admin_users is 'CITLog administrator accounts. Accessed only by the Flask backend with the server-side service role key.';
comment on table public.attendance is 'Signed faculty attendance records. RLS is enabled and no browser/client policies are granted.';
comment on table public.qr_tokens is 'Registered signed QR payload tokens generated from the protected admin dashboard.';
comment on table public.audit_logs is 'Durable administrative and security-relevant action log.';
